In [1]:
import numpy as np
import time

boyut = 1_000_000  # 1 milyon eleman

# Python listesi ile
liste = list(range(boyut))
baslangic = time.time()
sonuc_liste = [x * 2 for x in liste]
print(f"Liste süresi: {time.time() - baslangic:.4f} saniye")

# NumPy array ile
array = np.arange(boyut)
baslangic = time.time()
sonuc_array = array * 2
print(f"NumPy süresi: {time.time() - baslangic:.4f} saniye")

Liste süresi: 0.0143 saniye
NumPy süresi: 0.0011 saniye


In [2]:
# 1 Boyutlu array (vektör)
fiyatlar = np.array([150.0, 250.0, 80.0, 320.0, 95.0])

print(f"Tip: {type(fiyatlar)}")       # 
print(f"Veri tipi: {fiyatlar.dtype}") # float64
print(f"Boyut: {fiyatlar.ndim}")      # 1
print(f"Şekil: {fiyatlar.shape}")     # (5,)
print(f"Eleman sayısı: {fiyatlar.size}") # 5
print(f"Bellek (byte): {fiyatlar.nbytes}") # 40

# 2 Boyutlu array (matris)
# Satırlar: siparişler, Sütunlar: [ürün_fiyatı, adet, kargo]
siparisler = np.array([
    [150.0, 2, 29.9],
    [250.0, 1, 0.0],
    [80.0,  3, 49.9],
    [320.0, 1, 0.0],
])

print(f"\n2D Array şekli: {siparisler.shape}")  # (4, 3)
print(f"Satır sayısı: {siparisler.shape[0]}")    # 4
print(f"Sütun sayısı: {siparisler.shape[1]}")    # 3

Tip: <class 'numpy.ndarray'>
Veri tipi: float64
Boyut: 1
Şekil: (5,)
Eleman sayısı: 5
Bellek (byte): 40

2D Array şekli: (4, 3)
Satır sayısı: 4
Sütun sayısı: 3


In [ ]:
# Belirli değerle dolu
dolu = np.full((2, 3), 99.9)
print(dolu)

x = 5
y = 15
formul = (y - x) / 0.05 + 1
linspace_arr = np.linspace(x, y, int(formul)) # 5'ten 15'e kadar 0.5 adımlarla
print(linspace_arr)

[[99.9 99.9 99.9]
 [99.9 99.9 99.9]]
[ 5.    5.05  5.1   5.15  5.2   5.25  5.3   5.35  5.4   5.45  5.5   5.55
  5.6   5.65  5.7   5.75  5.8   5.85  5.9   5.95  6.    6.05  6.1   6.15
  6.2   6.25  6.3   6.35  6.4   6.45  6.5   6.55  6.6   6.65  6.7   6.75
  6.8   6.85  6.9   6.95  7.    7.05  7.1   7.15  7.2   7.25  7.3   7.35
  7.4   7.45  7.5   7.55  7.6   7.65  7.7   7.75  7.8   7.85  7.9   7.95
  8.    8.05  8.1   8.15  8.2   8.25  8.3   8.35  8.4   8.45  8.5   8.55
  8.6   8.65  8.7   8.75  8.8   8.85  8.9   8.95  9.    9.05  9.1   9.15
  9.2   9.25  9.3   9.35  9.4   9.45  9.5   9.55  9.6   9.65  9.7   9.75
  9.8   9.85  9.9   9.95 10.   10.05 10.1  10.15 10.2  10.25 10.3  10.35
 10.4  10.45 10.5  10.55 10.6  10.65 10.7  10.75 10.8  10.85 10.9  10.95
 11.   11.05 11.1  11.15 11.2  11.25 11.3  11.35 11.4  11.45 11.5  11.55
 11.6  11.65 11.7  11.75 11.8  11.85 11.9  11.95 12.   12.05 12.1  12.15
 12.2  12.25 12.3  12.35 12.4  12.45 12.5  12.55 12.6  12.65 12.7  12.75
 12.8  12.85 1

In [16]:
# 1D Array indeksleme
fiyatlar = np.array([150, 250, 80, 320, 95, 410, 175])

print(fiyatlar[0])    # 150 (ilk eleman)
print(fiyatlar[-1])   # 175 (son eleman)
print(fiyatlar[2:5])  # [80 320 95] (2. indeksten 4. indekse)
print(fiyatlar[:3])   # [150 250 80] (baştan 3 eleman)
print(fiyatlar[::2])  # [150 80 95 175] (2'şer atla)

# 2D Array indeksleme
siparisler = np.array([
    [10001, 150.0, 2],  # [siparis_id, fiyat, adet]
    [10002, 250.0, 1],
    [10003, 80.0,  3],
    [10004, 320.0, 1],
])

print(siparisler[0])         # İlk satır: [10001. 150.    2.]
print(siparisler[0, 1])      # 1. satır, 2. sütun: 150.0
print(siparisler[:, 1])      # Tüm satırlar, 2. sütun (tüm fiyatlar)
print(siparisler[1:3, 1:])   # 1-2. satırlar, 1. sütundan sona
print(siparisler[0,:2])

150
175
[ 80 320  95]
[150 250  80]
[150  80  95 175]
[1.0001e+04 1.5000e+02 2.0000e+00]
150.0
[150. 250.  80. 320.]
[[250.   1.]
 [ 80.   3.]]
[10001.   150.]


In [ ]:
# E-ticaret senaryo: Günlük satış verileri
gunluk_satis = np.array([45, 67, 89, 34, 56, 78, 92, 43, 65, 87])
urun_fiyati = 125.0  # TL

# Tüm satışların gelirini hesapla (döngü yok!)
gunluk_gelir = gunluk_satis * urun_fiyati
print("Günlük Gelirler (TL):")
print(gunluk_gelir)

# KDV ekle (%18)
kdvli_gelir = gunluk_gelir * 1.18
print(f"\nKDV dahil toplam: {kdvli_gelir.sum():,.2f} TL")

# İki array üzerinde işlem
satis_adedi   = np.array([10, 25, 8, 15, 30])
birim_fiyat   = np.array([200, 50, 500, 120, 80])
toplam_gelir  = satis_adedi * birim_fiyat  # Eleman bazlı çarpma
print("\nÜrün bazlı gelir:")
for i, gelir in enumerate(toplam_gelir):
    print(f"  Ürün {i+1}: {gelir:,} TL")

# Broadcasting: farklı boyutlu arraylarda işlem
# Haftalık satışlar (7 gün, 5 ürün)
haftalik = np.array([
    [10, 25, 8, 15, 30],
    [12, 22, 9, 18, 28],
    [8,  30, 7, 20, 35],
    [15, 20, 10, 12, 25],
    [11, 27, 6, 17, 32],
    [9,  24, 8, 14, 29],
    [13, 26, 11, 16, 31],
])

# Her ürünün fiyatı (5 eleman)
fiyatlar = np.array([200, 50, 500, 120, 80])

# Broadcasting: 7x5 * 5 = 7x5 (her satıra fiyatlar uygulanır)
haftalik_gelir = haftalik * fiyatlar
print(f"\nHaftalık toplam gelir: {haftalik_gelir.sum():,} TL")
print(f"Günlük ortalama gelir: {haftalik_gelir.sum(axis=1).mean():,.0f} TL")

In [25]:
baslangic = time.time()
nN = 10
aD = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
aW = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
aL = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
aR = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
vntK0 = 0.5
vntPI = 3.14159
vntZ = 1.0
vntRR = 1.0
vntUU = 0.0
for i in range(nN - 1):
        for j in range(i + 1, nN):
            # vntQ hesapla
            vntQ = 2 * ((aD[j] + aW[j]) * 2 - (aD[i] + aW[i]) * 2) + aD[j] * 2 - (aD[i] + 2 * aW[i]) * 2
           
            # vntL1 hesapla
            vntL1 = (aL[j] + aL[i]) / 2
           
            # vntK1 hesapla
            vntK1 = 1 - (aD[j] - aD[i] + 2 * aW[j]) / (2 * vntPI * vntL1)
           
            # aU(i,j) hesapla
            aU_ij = vntK0 * vntQ * vntK1 / (vntL1 * vntZ)
           
            # aU1(i,j) hesapla
            aU1_ij = aR[j] * aR[i] * aU_ij / vntRR ** 2
           
            vntUU += aU1_ij
bitis = time.time()
print(f"\nSonuç: {vntUU:.4f}")
print(f"Süre: {bitis - baslangic:.4f} saniye")


Sonuç: -508.6731
Süre: 0.0003 saniye


In [26]:
import numpy as np
baslangic = time.time()
nN = 10
aD = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
aW = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
aL = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
aR = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

vntK0 = 0.5
vntPI = 3.14159
vntZ = 1.0
vntRR = 1.0

# i ve j matrisleri
Di, Dj = aD[:, None], aD[None, :]
Wi, Wj = aW[:, None], aW[None, :]
Li, Lj = aL[:, None], aL[None, :]
Ri, Rj = aR[:, None], aR[None, :]

# vntQ
vntQ = 2 * ((Dj + Wj) * 2 - (Di + Wi) * 2) + Dj * 2 - (Di + 2 * Wi) * 2

# vntL1
vntL1 = (Lj + Li) / 2

# vntK1
vntK1 = 1 - (Dj - Di + 2 * Wj) / (2 * vntPI * vntL1)

# aU
aU = vntK0 * vntQ * vntK1 / (vntL1 * vntZ)

# aU1
aU1 = Rj * Ri * aU / (vntRR ** 2)

# sadece i < j için üst üçgen
mask = np.triu(np.ones((nN, nN), dtype=bool), k=1)

vntUU = np.sum(aU1[mask])

bitis = time.time()
print(f"Sonuç: {vntUU:.4f}")
print(f"Süre: {bitis - baslangic:.4f} saniye")

Sonuç: -508.6731
Süre: 0.0005 saniye
